// Generated by CoffeeScript 1.3.3
(function() {
  var fs, get;

  get = require('get');

  fs = require('fs');

  exports.index = function(req, res) {
    return res.render('index', {
      title: 'Welcome',
      layout: "layout",
      name: "Rishi Ishairzay"
    });
  };

}).call(this);
